### ISSUE TITLE
Feature request: Printer selection & metadata

### ISSUE THREAD

**Issue by Lazerbeak12345** [USUFSLC/usuprintcl#2]
It'd be nice to have a dropdown to be able to pick which printer you'd like and to say where it is (ex: TSC, Library, etc.)

I uploaded a file containing useful metadata that should include a few dozen more printers to the discord.

**Comment by emprespresso** [comment]
what's the advantage to this vs just sending it to the central server to be released anywhere on campus from a user's perspective?

**Comment by Lazerbeak12345** [comment]
Ah, I wasn't aware that was how it worked. NVM then.
